---
name: Kelly Sovacool
surname: 
position: 
address: 
phone: 
www: sovacool.dev
email: "sovacool@umich.edu"
twitter:
github: kelly-sovacool
linkedin: kelly-sovacool
date: "`r format(Sys.time(), '%B %Y')`"
mainfont: Helvetica
fontsize: 11pt
output: 
  vitae::moderncv:
    theme: classic
    latex_engine: xelatex
    keep_tex: true
    includes:
      in_header: preamble.tex
bibliography: cv/pubs.bib
#nocite: '@*' # ERROR ! You can't use `\vadjust' in vertical mode.
---

\hypersetup{urlcolor=ArboretumBlue} 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(glue)
library(here)
library(tidyverse)
library(vitae)
library(yaml)

read_yaml_as_tbl <- function(filepath) {
  read_yaml(filepath) %>%
    map_dfr(function(x) {
      sapply(names(x), function(y) {
        # wrap elements in list if length > 1
        if (length(x[[y]]) > 1) {
          x[[y]] <<- list(x[[y]])
        }
      })
      return(as_tibble_row(x))
    }) %>%
    return()
} 
replace_amps <- function(x) {
  return(str_replace_all(x, "&", "\\\\&"))
}
format_md2tex <- function(x) {
  return(x %>% 
           str_replace_all("_(.*)_", "\\\\textit{\\1}") %>%  # italics
           str_replace_all("\\*\\*(.*)\\*\\*", "\\\\textbf{\\1}") %>% # TODO bold
           str_replace_all('\\+', '\\\\plus') %>% 
           replace_amps()
         )
}

split_md_list <- function(x) {
  return(x %>% 
           str_remove('^- ') %>% 
           str_remove("\n$") %>% 
           str_split('\n- ')
         )
}
```
<!--
_Bioinformatician building and applying open source tools for microbiome research, and contributing to data science education along the way._
-->
# Education

```{r edu}
read_yaml_as_tbl(here('cv', 'edu.yml')) %>% 
  separate(inst, c('inst', 'detail'), sep = " <br> ") %>% 
  separate(inst, c('where', 'dept'), sep = ', ') %>% 
  detailed_entries(what = degree, 
                   when = dates, 
                   with = dept, 
                   where = where, 
                   why = detail)
```

# Skills

```{r skills}
read_yaml_as_tbl(here('cv','skills.yml')) %>%
  rowwise() %>% 
  mutate(categories = str_flatten(categories, ', ')) %>% 
  brief_entries(when = title, what = categories)
```

# Research Experience

```{r research}
read_yaml_as_tbl(here('cv', 'research.yml')) %>% 
  separate(lab, c('lab', 'inst'), sep = ", <br> ") %>% 
  mutate(why = tasks %>% format_md2tex() %>% split_md_list()
         ) %>% 
  detailed_entries(
    what = title,
    when = dates,
    with = lab,
    where = inst,
    why = why, 
    .protect = FALSE
  )
```

# Open Source Contributions

## Software

```{r software}
read_yaml_as_tbl(here('cv', 'software.yml')) %>% 
  detailed_entries(what = title, with = description, why = contrib)
```

## Curricula

```{r curricula}
read_yaml_as_tbl(here('cv', 'curricula.yml')) %>% 
  detailed_entries(what = title, with = description, why = contrib)
```

# Continuing Education

```{r continuing-edu}
read_yaml_as_tbl(here('cv', 'continuing-edu.yml')) %>% 
  brief_entries(what = glue("\\textbf{{{ title }}}") %>% replace_amps(), 
                when = date, 
                with = glue("{org}, {location}"), 
                .protect = FALSE)
```

# Teaching Experience

```{r teaching}
read_yaml_as_tbl(here('cv', 'teaching.yml')) %>% 
  detailed_entries(what = title,
                   when = dates,
                   with = org,
                   why = event,
                   where = where)
```

# Service

```{r service}
read_yaml_as_tbl(here('cv', 'service.yml')) %>% 
  mutate(why = tasks %>% format_md2tex() %>% split_md_list()
         ) %>% 
  detailed_entries(what = title, 
                   when = dates, 
                   with = org, 
                   why = why,
                   .protect = FALSE
                   )
```

# Presentations

## Talks

```{r talks}
read_yaml_as_tbl(here('cv', 'talks.yml')) %>% 
  brief_entries(what = glue("\\textbf{{{ event }}}"),
                when = date,
                with = glue("{format_md2tex(title)}. {location}"),
                .protect = FALSE)
```

## Posters

```{r posters}
read_yaml_as_tbl(here('cv', 'posters.yml')) %>% 
  brief_entries(what = glue("\\textbf{{{ event }}}"),
                when = date,
                with = glue("{format_md2tex(title)}. {location}"),
                .protect = FALSE)
```


# Awards

## Grants and Fellowships

```{r grants}
read_yaml_as_tbl(here('cv', 'grants.yml')) %>% 
  mutate(inst = str_replace(inst, " <br> ", ", "),
         title = str_replace(title, ' <br> ', ', ') %>% replace_amps(),
         amount = case_when(nchar(amount) != 0 ~ glue(' ({amount})') %>% 
                              str_replace("\\$", "\\\\$"),
                            TRUE ~ amount 
                            )
         ) %>% 
  brief_entries(what = glue("\\textbf{{{ title }}}"), 
                when = dates, 
                with = glue('{inst}{amount}'),
                .protect = FALSE)
```

## Honors

```{r honors}
read_yaml_as_tbl(here('cv', 'honors.yml')) %>% 
  brief_entries(what = glue("\\textbf{{{ title }}}"), 
                when = dates, 
                with = inst, 
                .protect = FALSE)
```

# Publications

**<sup>\*</sup>** Indicates co-first author


```{r pubs, results='asis'}
bib_entries <- read_yaml_as_tbl(here('cv','pubs.yml'))

raise_asterisk <- function(x) {
  return(str_replace_all(x, "\\*", "\\textsuperscript{*}"))
}

pubs <- bib_entries %>% 
  pull(bib_tex) %>% 
  sapply(., function(x) {
    glue::glue("\\item { x %>% replace_amps() %>% raise_asterisk() } 
               ")
  }) 
cat('\\small','\\begin{etaremune}', pubs, '\\end{etaremune}', sep = "\n")
```


