---
name: Kelly
surname: Sovacool
position: "PhD Candidate"
address: "University of Michigan"
phone: 
www: sovacool.dev
email: "sovacool@umich.edu"
twitter: kelly_sovacool
github: kelly-sovacool
linkedin: kelly-sovacool
date: "`r format(Sys.time(), '%B %Y')`"
fontsize: 12pt
fontfamily: sans
output: 
  vitae::moderncv:
    theme: classic
    latex_engine: xelatex
    includes:
      in_header: "preamble.tex"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(here)
library(tidyverse)
library(vitae)
library(yaml)
read_yaml_as_tbl <- function(filepath) {
  return(read_yaml(filepath) %>% 
           map_dfr(as_tibble_row)
  )
} 
split_md_list <- function(x) {
  return(x %>% 
           str_remove('^- ') %>% 
           str_remove("\n$") %>% 
           str_split('\n- '))
}
```

# Education

```{r edu}
read_yaml_as_tbl(here('cv', 'edu.yml'))%>% 
  separate(inst, c('inst', 'detail'), sep = " <br> ") %>% 
  separate(inst, c('where', 'dept'), sep = ', ') %>% 
  detailed_entries(what = degree, 
                   when = dates, 
                   with = dept, 
                   where = where, 
                   why = detail)
```

# Skills

```{r skills, eval = FALSE}
read_yaml_as_tbl(here('cv','skills.yml')) %>% 
  mutate(categories = split_md_list(categories)) %>% 
  vitae::brief_entries(when = title, what = categories)
```


# Research Experience

<!-- TODO: get italics to work inside entries -->

```{r research}
read_yaml_as_tbl(here('cv', 'research.yml')) %>% 
  separate(lab, c('lab', 'inst'), sep = ", <br> ") %>% 
  mutate(why = str_split(tasks %>% 
                           str_remove('^- ') %>% 
                           str_remove("\n$"),# %>% str_replace_all("_(.*)_", "\\textit{\\1}"), 
                         '\n- ')
         ) %>% 
  detailed_entries(
    what = title,
    with = lab,
    where = inst,
    when = dates,
    why = why#, .protect = FALSE # ERROR! Missing $ inserted. <inserted text> $ l.111 \end{itemize}}
  )
```

# Teaching Experience

```{r teaching}
read_yaml_as_tbl(here('cv', 'teaching.yml')) %>% 
  detailed_entries(what = title,
                   when = dates,
                   with = org,
                   why = event,
                   where = where)
```

# Service

```{r service}
read_yaml_as_tbl(here('cv', 'service.yml')) %>% 
  mutate(why = split_md_list(tasks))
```

# Open Source Contributions

## Software

```{r software}
read_yaml_as_tbl(here('cv', 'software.yml'))
```


# Publications

**\*** Indicates co-first author

```{r pubs}
bibliography_entries(here("cv_KLS.bib")) %>%
  arrange(issued)
```

